name: CI
on: [push, pull_request]
env:
  ProjectName: LibTemplate

jobs:
  check_format:
    name: Check format
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run dotnet format check
      run: dotnet format -wsa --check
